export const TECHNOLOGIES = [
  {
    name: 'HTML5',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg',
    tooltip: 'Structuring the web.',
    brandColor: 'rgba(227, 79, 38, 0.5)',
  },
  {
    name: 'CSS3',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg',
    tooltip: 'Styling beautiful interfaces.',
    brandColor: 'rgba(21, 114, 182, 0.5)',
  },
  {
    name: 'JavaScript',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
    tooltip: 'Adding interactive logic.',
    brandColor: 'rgba(247, 223, 30, 0.5)',
  },
  {
    name: 'TypeScript',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg',
    tooltip: 'Type-safe JavaScript.',
    brandColor: 'rgba(49, 120, 198, 0.5)',
  },
  {
    name: 'React',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg',
    tooltip: 'Building modern interfaces.',
    brandColor: 'rgba(97, 218, 251, 0.5)',
  },
  {
    name: 'Next.js',
    logo: 'https://cdn.simpleicons.org/nextdotjs/white',
    tooltip: 'React framework for production.',
    brandColor: 'rgba(255, 255, 255, 0.5)',
  },
  {
    name: 'Tailwind CSS',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg',
    tooltip: 'Utility-first styling.',
    brandColor: 'rgba(6, 182, 212, 0.5)',
  },
  {
    name: 'Framer Motion',
    logo: 'https://cdn.simpleicons.org/framer/0055FF',
    tooltip: 'Production-ready animations.',
    brandColor: 'rgba(0, 85, 255, 0.5)',
  },
  {
    name: 'GSAP',
    logo: 'https://cdn.simpleicons.org/greensock/88CE02',
    tooltip: 'Professional web animation.',
    brandColor: 'rgba(136, 206, 2, 0.5)',
  },
  {
    name: 'Node.js',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original.svg',
    tooltip: 'Backend runtime environment.',
    brandColor: 'rgba(51, 153, 51, 0.5)',
  },
  {
    name: 'Express.js',
    logo: 'https://cdn.simpleicons.org/express/white',
    tooltip: 'Fast web framework for Node.',
    brandColor: 'rgba(255, 255, 255, 0.5)',
  },
  {
    name: 'MongoDB',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mongodb/mongodb-original.svg',
    tooltip: 'NoSQL database.',
    brandColor: 'rgba(71, 162, 72, 0.5)',
  },
  {
    name: 'MySQL',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg',
    tooltip: 'Relational database management.',
    brandColor: 'rgba(68, 121, 161, 0.5)',
  },
  {
    name: 'Firebase',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/firebase/firebase-plain.svg',
    tooltip: 'Backend-as-a-service.',
    brandColor: 'rgba(255, 202, 40, 0.5)',
  },
  {
    name: 'AWS',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/amazonwebservices/amazonwebservices-original-wordmark.svg',
    tooltip: 'Cloud infrastructure.',
    brandColor: 'rgba(255, 153, 0, 0.5)',
  },
  {
    name: 'Docker',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/docker/docker-original.svg',
    tooltip: 'Containerized applications.',
    brandColor: 'rgba(36, 150, 237, 0.5)',
  },
  {
    name: 'Kubernetes',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/kubernetes/kubernetes-plain.svg',
    tooltip: 'Container orchestration.',
    brandColor: 'rgba(50, 108, 229, 0.5)',
  },
  {
    name: 'Git',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-original.svg',
    tooltip: 'Version control.',
    brandColor: 'rgba(240, 80, 50, 0.5)',
  },
  {
    name: 'GitHub',
    logo: 'https://cdn.simpleicons.org/github/white',
    tooltip: 'Code hosting and collaboration.',
    brandColor: 'rgba(255, 255, 255, 0.5)',
  },
  {
    name: 'Vite',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg',
    tooltip: 'Next-generation frontend tooling.',
    brandColor: 'rgba(100, 108, 255, 0.5)',
  },
  {
    name: 'Webpack',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/webpack/webpack-original.svg',
    tooltip: 'Module bundler.',
    brandColor: 'rgba(141, 214, 249, 0.5)',
  },
  {
    name: 'Postman',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postman/postman-original.svg',
    tooltip: 'API development platform.',
    brandColor: 'rgba(255, 108, 55, 0.5)',
  },
  {
    name: 'Cloudinary',
    logo: 'https://cdn.simpleicons.org/cloudinary/3448C5',
    tooltip: 'Image and video management.',
    brandColor: 'rgba(52, 72, 197, 0.5)',
  },
  {
    name: 'Mapbox',
    logo: 'https://cdn.simpleicons.org/mapbox/white',
    tooltip: 'Custom map integrations.',
    brandColor: 'rgba(255, 255, 255, 0.5)',
  },
  {
    name: 'OpenAI',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg',
    tooltip: 'AI model integrations.',
    brandColor: 'rgba(255, 255, 255, 0.5)',
    invert: true,
  },
  {
    name: 'REST API',
    logo: 'https://cdn.simpleicons.org/json/white',
    tooltip: 'Representational State Transfer.',
    brandColor: 'rgba(255, 255, 255, 0.5)',
  },
  {
    name: 'Render',
    logo: 'https://cdn.simpleicons.org/render/46E3B7',
    tooltip: 'Cloud application hosting.',
    brandColor: 'rgba(70, 227, 183, 0.5)',
  },
  {
    name: 'Vercel',
    logo: 'https://cdn.simpleicons.org/vercel/white',
    tooltip: 'Frontend deployment.',
    brandColor: 'rgba(255, 255, 255, 0.5)',
  },
  {
    name: 'Figma',
    logo: 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg',
    tooltip: 'Collaborative interface design.',
    brandColor: 'rgba(242, 78, 30, 0.5)',
  },
  {
    name: 'Google Apps Script',
    logo: 'https://cdn.simpleicons.org/googleappsscript/0B8043',
    tooltip: 'Automating Google Workspace.',
    brandColor: 'rgba(11, 128, 67, 0.5)',
  }
];
